-- Hyprland 配置文件（Lua）
-- 这是一个 Hyprland 窗口管理器的配置文件示例
--
-- 更多信息请参考官方 wiki: https://wiki.hypr.land/

--
-- 请注意，此处并未列出所有可用的设置/选项
-- 完整列表请查看 wiki
--

-- hl.config({ autogenerated = true }) -- 删除此行以移除警告提示

-- 显示器配置 - 详见 https://wiki.hypr.land/Configuring/Basics/Monitors/
-- 格式: monitor=[名称],分辨率@刷新率,位置,缩放
hl.monitor({ output = "", mode = "1920x1080@144", position = "auto", scale = 1.25 }) -- 自动配置显示器，1920x1080分辨率，144Hz刷新率，缩放比例1

-- 工作区配置
-- general.layout = "dwindle"
hl.config({ general = { layout = "scrolling" } })
-- Scrolling 布局：wrap_focus/swapcol = true 表示无限循环（默认）
-- general.wrap_focus = true
-- general.wrap_swapcol = true

-- 更多关键字配置请参考 https://wiki.hypr.land/Configuring/Start/

-- 启动时自动执行你喜欢的应用程序
-- hl.on("hyprland.start", function()
--     hl.exec_cmd("waybar & hyprpaper & firefox") -- 启动状态栏、壁纸和浏览器
-- end)

-- 引入其他配置文件（多文件配置）
-- require("myColors") -- 引入颜色配置

-- 设置常用程序变量
local terminal = "kitty"      -- 终端模拟器
local fileManager = "thunar"  -- 文件管理器
-- local fileManager = "kitty -e lf" -- 文件管理器（在kitty中运行lf）
local menu = "rofi -show drun" -- 应用程序启动器

-- 默认环境变量设置
hl.env("XCURSOR_SIZE", "24")                  -- 鼠标指针大小
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")       -- QT应用主题（如果有qt6ct可以改为qt6ct）

-- 输入法环境变量（fcitx5）
-- hl.env("GTK_IM_MODULE", "fcitx")            -- Wayland 下交给原生输入法前端，避免 fcitx5 诊断通知
hl.env("QT_IM_MODULE", "fcitx")               -- QT 应用使用 fcitx5
hl.env("XMODIFIERS", "@im=fcitx")             -- X11 应用使用 fcitx5
hl.env("SDL_IM_MODULE", "fcitx")              -- SDL 应用使用 fcitx5
hl.env("GLFW_IM_MODULE", "ibus")              -- GLFW 应用（某些游戏）

-- NVIDIA相关环境变量设置
hl.env("LIBVA_DRIVER_NAME", "nvidia")         -- 视频加速驱动
hl.env("XDG_SESSION_TYPE", "wayland")         -- 会话类型为Wayland
hl.env("GBM_BACKEND", "nvidia-drm")           -- 图形缓冲区管理后端
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia") -- GLX供应商库
hl.env("WLR_NO_HARDWARE_CURSORS", "1")        -- 禁用硬件光标
hl.env("QT_WAYLAND_FORCE_DPI", "120")         -- 强制QT应用DPI为120

-- 自启动程序
hl.on("hyprland.start", function()
    hl.exec_cmd([=[waybar -c ~/.config/waybar/Waybar-3.0/config -s ~/.config/waybar/Waybar-3.0/style.css -l top]=]) -- 启动状态栏
    hl.exec_cmd("fcitx5 --replace -d")        -- 启动输入法
    hl.exec_cmd([=[echo 'Xft.dpi:120' | xrdb]=]) -- 设置X资源数据库DPI
    hl.exec_cmd("mako")
    hl.exec_cmd("hyprpolkitagent")
    hl.exec_cmd("blueman-applet & nm-applet")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("waypaper --restore")
    hl.exec_cmd("v2rayN")
    hl.exec_cmd("Snipaste")          -- 启动 Snipaste 截图与贴图后台程序
end)

-- 所有配置类别详见 https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
    input = {
        kb_layout = "us",      -- 键盘布局为美式英语
        kb_variant = "",       -- 键盘变体
        kb_model = "",         -- 键盘型号
        kb_options = "",       -- 键盘选项
        kb_rules = "",         -- 键盘规则

        follow_mouse = 1,      -- 焦点跟随鼠标：1=是    

        touchpad = {
            natural_scroll = true, -- 自然滚动（类似苹果触控板）：关闭
        },

        sensitivity = 0,       -- 鼠标灵敏度：-1.0到1.0，0表示不修改
    },
})

hl.config({
    general = {
        -- 更多配置选项见 https://wiki.hypr.land/Configuring/Basics/Variables/

        gaps_in = 5,         -- 窗口之间的间隙大小（像素）
        gaps_out = 10,       -- 窗口与屏幕边缘的间隙大小（像素）
        border_size = 2,     -- 窗口边框大小（像素）
        col = {
            active_border = { colors = { "rgba(33ccffee)", "rgba(00ff99ee)" }, angle = 45 }, -- 活动窗口边框颜色（渐变）
            inactive_border = "rgba(595959aa)", -- 非活动窗口边框颜色
        },

        -- 开启撕裂模式前请先阅读 https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/
        allow_tearing = false, -- 是否允许画面撕裂（通常用于游戏等低延迟场景）

        snap = {
            -- 启用窗口捕捉
            enabled = true,
            -- 可选：调整捕捉参数
            window_gap = 5,
            monitor_gap = 10,
            border_overlap = true, --如果开启，两个窗口吸附后，它们之间只保留一个边框的宽度，而不是两个边框的宽度之和。
            respect_gaps = true, --是否考虑系统设置的整体窗口间隙（gaps_in）。
        },
    },
})

hl.config({
    decoration = {
        -- 更多装饰选项见 https://wiki.hypr.land/Configuring/Basics/Variables/

        rounding = 10,          -- 窗口圆角半径（像素）
        active_opacity = 0.99,  -- 活动窗口透明度：0.0-1.0
        inactive_opacity = 0.93, -- 非活动窗口透明度：0.0-1.0
        -- 窗口阴影
        -- 更多阴影选项见 https://wiki.hypr.land/Configuring/Basics/Variables/
        blur = {
            enabled = false, -- 这里可以正常注释
            -- size = 3,     -- 模糊大小
            -- passes = 1,   -- 模糊处理次数（越多越模糊，但性能消耗更大）
            -- xray = true,  -- X射线效果（透过窗口模糊）
            -- vibrancy = 0.1696, -- 模糊活力度（增加透明区域的对比度）
        },

        shadow = {
            -- enabled = true,         -- 启用阴影
            -- range = 10,             -- 阴影范围
            -- render_power = 3,       -- 渲染质量
            -- offset = { 3, 3 },      -- 阴影偏移（X Y）
            -- color = "rgba(1a1a1a66)", -- 半透明黑色阴影
        },

        -- 非活动窗口暗淡效果
        dim_inactive = true,
        dim_strength = 0.025, -- 暗淡强度：2.5%
        dim_special = 0.2,    -- 特殊工作区暗淡强度：20%
    },
})

hl.config({ animations = { enabled = true } }) -- 启用动画效果

-- 默认动画配置，更多信息见 https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/

hl.curve("myBezier", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } }) -- 自定义贝塞尔曲线（控制动画速度变化）

-- 动画格式：animation = 类型, 速度, 曲线类型, 额外参数
hl.animation({ leaf = "windows", enabled = true, speed = 7, bezier = "myBezier" }) -- 窗口打开动画
hl.animation({ leaf = "windowsOut", enabled = true, speed = 7, bezier = "default", style = "popin 80%" }) -- 窗口关闭动画
hl.animation({ leaf = "border", enabled = true, speed = 10, bezier = "default" }) -- 边框动画
hl.animation({ leaf = "borderangle", enabled = true, speed = 8, bezier = "default" }) -- 边框角度动画
hl.animation({ leaf = "fade", enabled = true, speed = 7, bezier = "default" }) -- 淡入淡出动画
hl.animation({ leaf = "workspaces", enabled = true, speed = 5, bezier = "default" }) -- 工作区切换动画
hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 4, bezier = "myBezier", style = "slidevert" }) -- 特殊工作区：垂直滑动（从上/下）

-- ~/.config/hypr/hyprland.conf 中的分组配置

hl.config({
    group = {
        -- 基础设置
        auto_group = true,                   -- 新窗口自动加入当前分组
        insert_after_current = true,         -- 新窗口插入当前窗口后
        focus_removed_window = true,         -- 移出窗口后自动聚焦
        drag_into_group = 1,                 -- 启用拖拽合并分组
        merge_groups_on_drag = true,         -- 允许分组间拖拽合并

        -- 边框颜色（可自定义）
        col = {
            border_active = 0x66ffff00,        -- 活动分组边框（黄色）
            border_inactive = 0x66777700,      -- 非活动分组边框（暗黄色）
            border_locked_active = 0x66ff6b4d, -- 橙色 - 锁定活跃组
            border_locked_inactive = 0x66555555, -- 中灰色 - 锁定非活跃组
        },

        -- 分组栏美化配置
        groupbar = {
            enabled = true,
            font_family = "JetBrains Mono Nerd Font",
            font_size = 17,
            height = 10,
            gradients = true,
            render_titles = true,
            scrolling = true,

            -- 圆角设计
            rounding = 4,
            rounding_power = 3.0,
            gradient_rounding = 6,
            gradient_rounding_power = 3.0,

            -- 间距调整
            gaps_in = 3,
            gaps_out = 4,
            indicator_height = 2,
            indicator_gap = 2,

            -- 文字颜色
            text_color = "0xffeeeeee",
            text_color_inactive = "0x77ffffff",
            text_color_locked_active = "0xffff6b4d",
            text_color_locked_inactive = "0x77ff6b4d",

            -- 背景渐变颜色
            col = {
                active = 0x3344aaff,          -- 半透明蓝色
                inactive = 0x1a333333,        -- 深色半透明
                locked_active = 0x33ff6b4d,   -- 半透明橙色
                locked_inactive = 0x1a555555, -- 中灰色半透明
            },
        },
    },
})

hl.config({
    dwindle = {
        -- 交错式布局配置，详见 https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/
        preserve_split = true, -- 保持分割方向（强烈建议启用）
    },
})

hl.config({
    master = {
        -- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
        mfact = 0.5,                  -- 主窗口区域占比（0.0-1.0）
        orientation = "left",         -- 主窗口位置：left, right, top, bottom
        special_scale_factor = 0.8,   -- 特殊工作区的缩放因子
        new_status = "master",        -- 新窗口状态：master, stack
    },
})

hl.config({
    scrolling = {
        -- 滚动布局配置 (Hyprland 0.54+)
        fullscreen_on_one_column = true, -- 单列时全屏显示
        column_width = 0.7,              -- 列默认宽度(50%屏幕宽度)
        direction = "right",             -- 新窗口方向和滚动方向: left/right/down/up
        follow_focus = true,             -- 焦点切换时自动滚动显示窗口
        focus_fit_method = 0,            -- 聚焦时视图调整: 0=居中, 1=适配
        follow_min_visible = 0.4,        -- 焦点窗口至少可见比例
        explicit_column_widths = "0.333,0.5,0.667,0.85,1.0", -- 预配置列宽
        -- wrap_focus = true,            -- ✅ 启用循环聚焦
        -- wrap_swapcol = true,          -- ✅ 启用循环交换
    },
})

-- 触控板手势配置，详见 https://wiki.hypr.land/Configuring/Advanced-and-Cool/Gestures/
-- hl.config({
--     gestures = {
--         workspace_swipe = false, -- 是否启用工作区滑动切换（默认关闭）
--     },
-- })

hl.config({
    misc = {
        -- 杂项配置，详见 https://wiki.hypr.land/Configuring/Basics/Variables/
        force_default_wallpaper = -1, -- 默认壁纸设置：-1=自动，0=禁用，1=启用（设为0或1可禁用动漫吉祥物壁纸）
        focus_on_activate = true,     -- 允许点击通知时聚焦对应应用窗口
    },
})

-- -------- 绑定设置 --------
hl.config({
    binds = {
        -- scroll_event_delay = 0, -- 滚动事件延迟
        hide_special_on_workspace_change = true, -- 工作区切换时隐藏特殊工作区
    },
})

-- 设备特定配置示例
-- 详见 https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/
hl.device({
    name = "epic-mouse-v1", -- 设备名称
    sensitivity = -0.5,     -- 该设备的特定灵敏度设置
})

hl.config({
    xwayland = {
        force_zero_scaling = true,
    },
})

-- 更多关键字配置见 https://wiki.hypr.land/Configuring/Start/
local mainMod = "SUPER" -- 定义主修饰键为Super键（Windows键/Command键）

-- 快捷键绑定示例，更多配置见 https://wiki.hypr.land/Configuring/Basics/Binds/
hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal)) -- Super+Q: 启动终端
hl.bind(mainMod .. " + C", function()
    local window = hl.get_active_window()
    if window and window.class == "ceru-music" then
        hl.exec_cmd("$HOME/.config/hypr/scripts/tray.py ceru") -- Ceru Music: 隐藏到托盘
        return
    end
    if window and window.class == "python3" and window.title == "有道词典" then
        hl.exec_cmd("$HOME/.config/hypr/scripts/tray.py youdao") -- 有道词典: 隐藏到托盘
        return
    end
    hl.exec_cmd("hyprctl dispatch 'hl.dsp.window.close()'") -- 其他窗口：正常关闭
end)
hl.bind(mainMod .. " + M", hl.dsp.exit()) -- Super+M: 退出Hyprland
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager)) -- Super+E: 启动文件管理器
hl.bind(mainMod .. " + Space", hl.dsp.window.float({ action = "toggle" })) -- Super+V: 切换窗口浮动/平铺状态
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(menu)) -- Super+R: 启动应用程序菜单
hl.bind(mainMod .. " + T", hl.dsp.exec_cmd([=[grim -g "$(slurp)" - | wl-copy --type image/png]=])) -- Super+T: 框选截图到剪贴板
hl.bind("F1", hl.dsp.exec_cmd("Snipaste snip -o clipboard")) -- F1: Snipaste 框选并复制到剪贴板
hl.bind("F3", hl.dsp.exec_cmd("Snipaste paste")) -- F3: 将剪贴板图片贴到屏幕
hl.bind("ALT + X", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/youdao.py")) -- Alt+X: 打开或隐藏有道词典

hl.bind(mainMod .. " + F12", hl.dsp.exec_cmd("pkill -SIGUSR2 waybar"))
hl.bind(mainMod .. " + V", hl.dsp.exec_cmd("pkill -SIGUSR1 waybar")) -- 切换 waybar 显示/隐藏
hl.bind(mainMod .. " + SHIFT + V", hl.dsp.exec_cmd([=[pkill waybar; waybar -c ~/.config/waybar/Waybar-3.0/config -s ~/.config/waybar/Waybar-3.0/style.css -l top &]=])) -- 重新启动 waybar
hl.bind("CTRL + SHIFT + ESCAPE", hl.dsp.exec_cmd("missioncenter")) -- 启动任务中心

-- -------- 布局类型切换 --------
-- 切换到特定布局（带通知）
hl.bind(mainMod .. " + F1", function() hl.config({ general = { layout = "dwindle" } }) end)
hl.bind(mainMod .. " + F2", function() hl.config({ general = { layout = "master" } }) end)
hl.bind(mainMod .. " + F3", function() hl.config({ general = { layout = "scrolling" } }) end)
hl.bind(mainMod .. " + F4", function() hl.config({ general = { layout = "monocle" } }) end)

-- -------- Waybar 快捷键 --------
hl.bind(mainMod .. " + Z", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/waybar_auto_hide.py")) -- 切换 waybar 显示/隐藏并同步外边距

-- 只在当前布局支持对应消息时执行，避免切换布局后触发运行时错误
local function layout_bind(dispatchers)
    return function()
        local workspace = hl.get_active_workspace()
        local dispatcher = workspace and dispatchers[workspace.tiled_layout]
        if dispatcher then hl.dispatch(dispatcher) end
    end
end

-- -------- Scrolling 布局专用快捷键 --------
-- 左右滚动（移动视图）
hl.bind(mainMod .. " + A", layout_bind({ scrolling = hl.dsp.layout("move -col"), monocle = hl.dsp.layout("cyclenext"), master = hl.dsp.focus({ direction = "left" }), dwindle = hl.dsp.focus({ direction = "left" }) })) -- Super+A: 左（scrolling滚动 / monocle下一个 / master·dwindle焦点左移）
hl.bind(mainMod .. " + D", layout_bind({ scrolling = hl.dsp.layout("move +col"), monocle = hl.dsp.layout("cycleprev"), master = hl.dsp.focus({ direction = "right" }), dwindle = hl.dsp.focus({ direction = "right" }) })) -- Super+D: 右（scrolling滚动 / monocle上一个 / master·dwindle焦点右移）
hl.bind(mainMod .. " + SHIFT + D", layout_bind({ scrolling = hl.dsp.layout("colresize +conf") })) -- Super+Shift+D: 增加列宽（循环预设值）
hl.bind(mainMod .. " + SHIFT + A", layout_bind({ scrolling = hl.dsp.layout("colresize -conf") })) -- Super+Shift+A: 减少列宽（循环预设值）
hl.bind("ALT + mouse_up", layout_bind({ scrolling = hl.dsp.layout("swapcol r") })) -- Alt+ 滚轮下：与右侧列交换
hl.bind("ALT + mouse_down", layout_bind({ scrolling = hl.dsp.layout("swapcol l") })) -- Alt+ 滚轮上：与左侧列交换

-- Monocle 布局：窗口切换（单窗口模式下循环窗口）
-- Super+A / Super+D 已在上方根据当前布局分流
hl.bind("ALT + grave", hl.dsp.window.fullscreen()) -- Alt+`: 切换窗口全屏/恢复

-- dwindle布局: 切换模式
-- hl.bind(mainMod .. " + P", hl.dsp.window.pseudo()) -- Super+P: 切换伪平铺模式（dwindle布局）
-- hl.bind(mainMod .. " + X", layout_bind({ dwindle = hl.dsp.layout("togglesplit") })) -- Super+X: 切换分割方向（dwindle布局）



-- -- 进入窗口管理模式
-- hl.bind("SUPER + W", hl.dsp.submap("window_manage"))
-- -- 窗口管理模式定义
-- hl.define_submap("window_manage", function()
--     -- 使用 WASD 移动焦点
--     hl.bind("A", hl.dsp.focus({ direction = "l" }))
--     hl.bind("D", hl.dsp.focus({ direction = "r" }))
--     hl.bind("W", hl.dsp.focus({ direction = "u" }))
--     hl.bind("S", hl.dsp.focus({ direction = "d" }))
--     -- 循环切换窗口
--     hl.bind("TAB", hl.dsp.window.cycle_next())
--     -- 左右切换工作区
--     -- hl.bind("E", hl.dsp.focus({ workspace = "+1" }))
--     -- hl.bind("Q", hl.dsp.focus({ workspace = "-1" }))
--     -- 移动窗口
--     hl.bind("SHIFT + A", hl.dsp.window.move({ direction = "l" }))
--     hl.bind("SHIFT + D", hl.dsp.window.move({ direction = "r" }))
--     hl.bind("SHIFT + W", hl.dsp.window.move({ direction = "u" }))
--     hl.bind("SHIFT + S", hl.dsp.window.move({ direction = "d" }))
--     -- 调整窗口大小
--     hl.bind("ALT + W", hl.dsp.window.resize({ x = 0, y = -20, relative = true }))
--     hl.bind("ALT + S", hl.dsp.window.resize({ x = 0, y = 20, relative = true }))
--     hl.bind("ALT + A", hl.dsp.window.resize({ x = -20, y = 0, relative = true }))
--     hl.bind("ALT + D", hl.dsp.window.resize({ x = 20, y = 0, relative = true }))
--     -- 退出模式
--     hl.bind("C", hl.dsp.submap("reset"))
--     hl.bind("Q", hl.dsp.submap("reset"))
--     hl.bind("ESCAPE", hl.dsp.submap("reset"))
-- end)

-- 使用主修饰键+数字键切换工作区
hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 })) -- Super+1: 切换到工作区1
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 })) -- Super+2: 切换到工作区2
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 })) -- Super+3: 切换到工作区3
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 })) -- Super+4: 切换到工作区4
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 })) -- Super+5: 切换到工作区5
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 })) -- Super+6: 切换到工作区6
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 })) -- Super+7: 切换到工作区7
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 })) -- Super+8: 切换到工作区8
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = 9 })) -- Super+9: 切换到工作区9
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 })) -- Super+0: 切换到工作区10

-- 使用主修饰键+Shift+数字键将活动窗口移动到指定工作区
hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1 })) -- Super+Shift+1: 将当前窗口移动到工作区1
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2 })) -- Super+Shift+2: 将当前窗口移动到工作区2
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3 })) -- Super+Shift+3: 将当前窗口移动到工作区3
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4 })) -- Super+Shift+4: 将当前窗口移动到工作区4
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5 })) -- Super+Shift+5: 将当前窗口移动到工作区5
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6 })) -- Super+Shift+6: 将当前窗口移动到工作区6
hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7 })) -- Super+Shift+7: 将当前窗口移动到工作区7
hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8 })) -- Super+Shift+8: 将当前窗口移动到工作区8
hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9 })) -- Super+Shift+9: 将当前窗口移动到工作区9
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10 })) -- Super+Shift+0: 将当前窗口移动到工作区10

-- 特殊工作区（临时工作区/便签本）配置
hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic")) -- Super+S: 切换显示/隐藏特殊工作区
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" })) -- Super+Shift+S: 将当前窗口移动到特殊工作区

-- 使用主修饰键+鼠标滚轮切换工作区
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e-1" })) -- Super+鼠标滚轮向下: 切换到上一个工作区
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e+1" })) -- Super+鼠标滚轮向上: 切换到下一个工作区

-- 使用主修饰键+鼠标左/右键拖动来移动/调整窗口大小
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true }) -- Super+鼠标左键拖动: 移动窗口
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true }) -- Super+鼠标右键拖动: 调整窗口大小


-- -------- 硬件按键绑定 --------
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set 5%+"), { locked = true, repeating = true }) -- 增加亮度
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 5%-"), { locked = true, repeating = true }) -- 降低亮度
hl.bind("XF86KbdBrightnessUp", hl.dsp.exec_cmd("brightnessctl set 5%+"), { locked = true, repeating = true }) -- 键盘背光增加（某些笔记本）
hl.bind("XF86KbdBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 5%-"), { locked = true, repeating = true }) -- 键盘背光降低（某些笔记本）

-- 音量控制
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%+"), { locked = true, repeating = true }) -- [hidden] 增加音量
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%-"), { locked = true, repeating = true }) -- [hidden] 降低音量
-- 静音控制
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_SINK@ toggle"), { locked = true }) -- [hidden] 切换静音
-- 麦克风控制
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_SOURCE@ toggle"), { locked = true }) -- [hidden] 切换麦克风静音 (硬件按键)

-- -------- 分组相关 --------
hl.bind(mainMod .. " + G", hl.dsp.group.toggle()) -- Super+G: 切换当前窗口的分组状态（加入/移出）
hl.bind(mainMod .. " + SHIFT + G", hl.dsp.window.move({ out_of_group = true })) -- Super+Shift+G: 将当前窗口移出分组
hl.bind(mainMod .. " + L", hl.dsp.group.lock_active({ action = "toggle" })) -- Super+L: 锁定分组管理
hl.bind(mainMod .. " + Tab", hl.dsp.group.next()) -- Super+Tab: 切换分组内的窗口（循环）
hl.bind(mainMod .. " + SHIFT + Tab", hl.dsp.group.prev()) -- Super+Shift+Tab: 切换分组内的窗口（反向）


-- -------- 窗口管理 --------

-- [hidden] 收起/恢复当前工作区的浮动窗口
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/toggle_workspace_floats.py"))

-- -------- 窗口移动 --------
-- hl.bind("SUPER + SHIFT + left/up/right/down", ...) -- 方向键移动窗口 (注释格式)
hl.bind("ALT + A", hl.dsp.window.move({ direction = "l" })) -- [hidden] 向左移动窗口
hl.bind("ALT + D", hl.dsp.window.move({ direction = "r" })) -- [hidden] 向右移动窗口
hl.bind("ALT + W", hl.dsp.window.move({ direction = "u" })) -- [hidden] 向上移动窗口
hl.bind("ALT + S", hl.dsp.window.move({ direction = "d" })) -- [hidden] 向下移动窗口

-- -------- 窗口循环 --------
-- [hidden] Alt+Tab：有浮动窗口时循环浮动窗口，没有浮动窗口时循环平铺窗口
-- 注意：函数内直接调用 hl.dsp.* 在按键回调上下文里不生效（Hyprland 0.56 quirk），
-- 所以切换动作经 hl.exec_cmd + hyprctl dispatch 走已验证可用的路径
hl.bind("ALT + Tab", function()
    local ws = hl.get_active_workspace()
    local floats = 0
    if ws then
        for _, w in ipairs(hl.get_workspace_windows(ws)) do
            if w.floating then floats = floats + 1 end
        end
    end
    if floats > 0 then
        hl.exec_cmd("hyprctl dispatch 'hl.dsp.window.cycle_next({ next = false, floating = true })' && hyprctl dispatch 'hl.dsp.window.bring_to_top()'")
    elseif ws and ws.tiled_layout == "scrolling" then
        hl.exec_cmd("hyprctl dispatch 'hl.dsp.layout(\"focus r\")' && hyprctl dispatch 'hl.dsp.window.bring_to_top()'")
    else
        hl.exec_cmd("hyprctl dispatch 'hl.dsp.window.cycle_next({ next = false, tiled = true })' && hyprctl dispatch 'hl.dsp.window.bring_to_top()'")
    end
end)

-- -------- 窗口循环 --------
hl.bind("ALT + ESCAPE", hl.dsp.exec_cmd("niflveil minimize"))
hl.bind("ALT + R", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/niflveil-restore")) -- [hidden] rofi 恢复菜单（替代 eww）


-- -------- 窗口规则配置 --------

-- XMind：浮动弹窗默认居中；平铺主窗在 Scrolling 布局中占满一列
hl.window_rule({ match = { class = "^(Xmind)$", float = true }, center = true })
hl.window_rule({ match = { class = "^(Xmind)$", float = false }, scrolling_width = 1.0 })

-- 嘉立创 EDA 专业版：在 Scrolling 布局中默认占满一列
hl.window_rule({ match = { class = "^(jlceda-pro)$", float = false }, scrolling_width = 1.0 })

-- Blender：主窗口在 Scrolling 布局中占满一列
hl.window_rule({ match = { class = "^(blender)$", title = ".* - Blender.*" }, scrolling_width = 1.0 })

-- Blender 文件窗口：默认浮动、居中，尺寸为显示器的 50% × 60%
hl.window_rule({ match = { class = "^(blender)$", title = "^(Blender文件视图)$" }, float = true })
hl.window_rule({ match = { class = "^(blender)$", title = "^(Blender文件视图)$" }, size = "(monitor_w*0.50) (monitor_h*0.60)" })
hl.window_rule({ match = { class = "^(blender)$", title = "^(Blender文件视图)$" }, center = true })

-- Waypaper 壁纸工具浮动
hl.window_rule({ match = { class = "^(waypaper)$" }, float = true })

-- v2rayN 主窗口默认浮动、居中，尺寸为 75% × 85%
hl.window_rule({ match = { class = "^(v2rayN)$" }, float = true })
hl.window_rule({ match = { class = "^(v2rayN)$" }, size = "(monitor_w*0.75) (monitor_h*0.85)" })
hl.window_rule({ match = { class = "^(v2rayN)$" }, center = true })

-- 任务中心浮动
hl.window_rule({ match = { class = "^(io.missioncenter.MissionCenter)$" }, float = true })
hl.window_rule({ match = { class = "^(io.missioncenter.MissionCenter)$" }, size = "(monitor_w*0.75) (monitor_h*0.80)" })
hl.window_rule({ match = { class = "^(io.missioncenter.MissionCenter)$" }, center = true })

-- OBS/Wayland 屏幕共享选择器默认浮动、居中，尺寸为 45% × 60%
hl.window_rule({ match = { class = "^(hyprland-share-picker)$" }, float = true })
hl.window_rule({ match = { class = "^(hyprland-share-picker)$" }, size = "(monitor_w*0.45) (monitor_h*0.60)" })
hl.window_rule({ match = { class = "^(hyprland-share-picker)$" }, center = true })

-- Gradia 截图工具浮动
hl.window_rule({ match = { class = "^(be.alexandervanhee.gradia)$" }, float = true })

-- Snipaste 的贴图窗口通过 XWayland 运行；避免焦点与特效重绘造成闪烁。
hl.window_rule({ match = { class = "^(Snipaste)$" }, float = true })
hl.window_rule({ match = { class = "^(Snipaste)$" }, focus_on_activate = false })
hl.window_rule({ match = { class = "^(Snipaste)$" }, suppress_event = "maximize" })
hl.window_rule({ match = { class = "^(Snipaste)$" }, no_anim = true })
hl.window_rule({ match = { class = "^(Snipaste)$" }, no_blur = true })
hl.window_rule({ match = { class = "^(Snipaste)$" }, no_shadow = true })

-- 哔哩哔哩默认浮动、居中，尺寸为显示器的 90% × 85%
hl.window_rule({ match = { class = "^(bilibili)$" }, float = true })
hl.window_rule({ match = { class = "^(bilibili)$" }, size = "(monitor_w*0.80) (monitor_h*0.85)" })
hl.window_rule({ match = { class = "^(bilibili)$" }, center = true })

-- 哔哩哔哩独立播放小窗口使用视频标题，缩小至 67% × 75% 并居中
hl.window_rule({ match = { class = "^(bilibili)$", title = "negative:.*-bilibili$" }, size = "(monitor_w*0.67) (monitor_h*0.75)" })
hl.window_rule({ match = { class = "^(bilibili)$", title = "negative:.*-bilibili$" }, center = true })

-- mpv 原生 Wayland 窗口默认浮动
hl.window_rule({ match = { class = "^(mpv)$" }, float = true })

-- Spotify 默认浮动
hl.window_rule({ match = { class = "^(spotify)$" }, float = true })

-- Ceru Music 默认浮动
hl.window_rule({ match = { class = "^(ceru-music)$" }, float = true })

-- 有道词典默认浮动
hl.window_rule({ match = { class = "^(python3)$", title = "^(有道词典)$" }, float = true })

-- 图片保存对话框浮动
hl.window_rule({ match = { title = "^(Save Image As)$" }, float = true })

-- GTK/XDG Portal 文件选择对话框默认浮动、居中，尺寸为 55% × 70%
hl.window_rule({ match = { class = "^(xdg-desktop-portal-gtk)$" }, float = true })
hl.window_rule({ match = { class = "^(xdg-desktop-portal-gtk)$" }, size = "(monitor_w*0.55) (monitor_h*0.70)" })
hl.window_rule({ match = { class = "^(xdg-desktop-portal-gtk)$" }, center = true })

-- Zen 浏览器默认浮动、居中，尺寸为显示器的 95% × 90%
hl.window_rule({ match = { class = "^(zen)$" }, float = true })
hl.window_rule({ match = { class = "^(zen)$" }, size = "(monitor_w*0.95) (monitor_h*0.90)" })
hl.window_rule({ match = { class = "^(zen)$" }, center = true })
hl.window_rule({ match = { class = "^(zen)$" }, scrolling_width = 1.0 })

-- 滚动布局下占满宽度
hl.window_rule({ match = { class = "^(trae)$" }, scrolling_width = 1.0 })
hl.window_rule({ match = { class = "^(code)$" }, scrolling_width = 1.0 })

-- GNOME 软件中心浮动
hl.window_rule({ match = { class = "^(org.gnome.Software)$" }, float = true })

-- Thunar 文件管理器浮动
hl.window_rule({ match = { class = "^(thunar)$" }, float = true })
hl.window_rule({ match = { class = "^(thunar)$" }, size = "(monitor_w*0.55) (monitor_h*0.70)" })
hl.window_rule({ match = { class = "^(thunar)$" }, center = true })

-- QQ 窗口浮动（注意：类名通常是小写，先用 hyprctl clients 确认）
-- hl.window_rule({ match = { class = "^(qq)$" }, float = true })
-- hl.window_rule({ match = { class = "^(qq)$" }, size = "(monitor_w*0.75) (monitor_h*0.85)" })
-- hl.window_rule({ match = { class = "^(qq)$" }, center = true })

-- 提示：使用 hyprctl clients 查看窗口的 class 和 title
